import type { ResourceDefinition } from '../shared';

const nameColorOptions = [
	{ name: 'Blue', value: 'blue' },
	{ name: 'Default', value: 'default' },
	{ name: 'Gold', value: 'gold' },
	{ name: 'Green', value: 'green' },
	{ name: 'Light Blue', value: 'lightblue' },
	{ name: 'Light Green', value: 'lightgreen' },
	{ name: 'Orange', value: 'orange' },
	{ name: 'Pink', value: 'pink' },
	{ name: 'Purple', value: 'purple' },
	{ name: 'Red', value: 'red' },
];

export const usersResource: ResourceDefinition = {
	name: 'Users',
	value: 'users',
	operations: [
		{
			name: 'Get Me',
			value: 'me',
			method: 'GET',
			path: '/APP/Users/me',
			description: 'Get current user information',
			action: 'Get current user information',
		},
		{
			name: 'Update',
			value: 'update',
			method: 'POST',
			path: '/APP/Users/update',
			description: 'Update current user information',
			action: 'Update current user information',
			params: [
				{ displayName: 'Full Name', name: 'full_name', type: 'string', default: '' },
				{ displayName: 'Display Name', name: 'display_name', type: 'string', default: '' },
				{ displayName: 'Gender', name: 'gender', type: 'string', default: '' },
				{
					displayName: 'Name Color',
					name: 'name_color',
					type: 'options',
					default: '',
					options: [{ name: 'Unset', value: '' }, ...nameColorOptions],
				},
				{
					displayName: 'Date Of Birth',
					name: 'date_of_birth',
					type: 'string',
					default: '',
					description: 'YYYY-MM-DD',
				},
				{ displayName: 'Birthday Privacy', name: 'birthday_privacy', type: 'string', default: '' },
				{ displayName: 'Country ID', name: 'country_id', type: 'string', default: '' },
				{ displayName: 'Relationship', name: 'relationship', type: 'string', default: '' },
				{ displayName: 'About', name: 'about', type: 'string', default: '', rows: 4 },
				{
					displayName: 'Email',
					name: 'email',
					type: 'string',
					default: '',
					placeholder: 'name@email.com',
				},
				{
					displayName: 'Privacy',
					name: 'privacy',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Only Friends', value: 'only_friends' },
						{ name: 'World', value: 'world' },
					],
				},
				{ displayName: 'Creature', name: 'creature', type: 'string', default: '' },
				{ displayName: 'Creature Special', name: 'creature_special', type: 'string', default: '' },
				{
					displayName: 'Filter Porn',
					name: 'filter_porn',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: '0', value: '0' },
						{ name: '1', value: '1' },
						{ name: '2', value: '2' },
					],
				},
				{
					displayName: 'Filter Anonymous',
					name: 'filter_anonymous',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: '0', value: '0' },
						{ name: '1', value: '1' },
					],
				},
				{ displayName: 'Filter Keywords', name: 'filter_keywords', type: 'string', default: '' },
				{ displayName: 'Pinned Plurk ID', name: 'pinned_plurk_id', type: 'string', default: '' },
				{
					displayName: 'Friend List Privacy',
					name: 'friend_list_privacy',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Friends Only', value: 'friends-only' },
						{ name: 'Only Me', value: 'only-me' },
						{ name: 'Public', value: 'public' },
					],
				},
				{
					displayName: 'Accept Gift',
					name: 'accept_gift',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Always', value: 'always' },
						{ name: 'Friends Only', value: 'friends-only' },
						{ name: 'Never', value: 'never' },
					],
				},
				{
					displayName: 'Accept Private Plurk',
					name: 'accept_private_plurk',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'All', value: 'all' },
						{ name: 'Friends', value: 'friends' },
						{ name: 'None', value: 'none' },
					],
				},
			],
		},
		{
			name: 'Update Background',
			value: 'updateBackground',
			method: 'POST',
			path: '/APP/Users/updateBackground',
			description: 'Update current user background',
			action: 'Update current user background',
			fileParam: {
				apiName: 'bg_image',
				defaultBinaryProperty: 'data',
				description: 'Binary property that contains the background image',
			},
		},
		{
			name: 'Set Name Color',
			value: 'setNameColor',
			method: 'POST',
			path: '/APP/Users/setNameColor',
			description: 'Set profile name color',
			action: 'Set profile name color',
			params: [
				{
					displayName: 'Color',
					name: 'color',
					type: 'options',
					default: 'default',
					options: nameColorOptions,
				},
			],
		},
		{
			name: 'Get Karma Stats',
			value: 'getKarmaStats',
			method: 'GET',
			path: '/APP/Users/getKarmaStats',
			description: 'Get current user karma statistics',
			action: 'Get current user karma statistics',
		},
		{
			name: 'Get Aliases',
			value: 'getAliases',
			method: 'GET',
			path: '/APP/Users/getAliases',
			description: 'Get user aliases',
			action: 'Get user aliases',
		},
		{
			name: 'Set Alias',
			value: 'setAlias',
			method: 'POST',
			path: '/APP/Users/setAlias',
			description: 'Set a user alias',
			action: 'Set a user alias',
			params: [
				{ displayName: 'User ID', name: 'user_id', type: 'string', default: '' },
				{ displayName: 'Alias', name: 'alias', type: 'string', default: '' },
			],
		},
		{
			name: 'Set Phone Number',
			value: 'setPhoneNumber',
			method: 'POST',
			path: '/APP/Users/setPhoneNumber',
			description: 'Update the account phone number',
			action: 'Set phone number',
			params: [{ displayName: 'Phone Number', name: 'phone_number', type: 'string', default: '' }],
		},
		{
			name: 'Resend Phone Verification Number',
			value: 'resendPhoneVerificationNumber',
			method: 'POST',
			path: '/APP/Users/resendPhoneVerificationNumber',
			description: 'Send a new phone verification code',
			action: 'Resend phone verification number',
		},
		{
			name: 'Verify Phone Number',
			value: 'verifyPhoneNumber',
			method: 'POST',
			path: '/APP/Users/verifyPhoneNumber',
			description: 'Verify the account phone number',
			action: 'Verify phone number',
			params: [{ displayName: 'Verify Code', name: 'verify_code', type: 'string', default: '' }],
		},
		{
			name: 'Get Mail Notifications',
			value: 'getMailNotifications',
			method: 'GET',
			path: '/APP/Users/getMailNotifications',
			description: 'Get mail notification settings',
			action: 'Get mail notification settings',
		},
		{
			name: 'Set Mail Notifications',
			value: 'setMailNotifications',
			method: 'POST',
			path: '/APP/Users/setMailNotifications',
			description: 'Set mail notification settings',
			action: 'Set mail notification settings',
			params: [{ displayName: 'Accepts', name: 'accepts', type: 'string', default: '' }],
		},
		{
			name: 'Set Private Plurk Acceptence',
			value: 'setPrivatePlurkAcceptence',
			method: 'POST',
			path: '/APP/Users/setPrivatePlurkAcceptence',
			description: 'Set private Plurk acceptance scope',
			action: 'Set private Plurk acceptance scope',
			params: [
				{
					displayName: 'Scope',
					name: 'scope',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'All', value: 'all' },
						{ name: 'Friends', value: 'friends' },
						{ name: 'None', value: 'none' },
					],
				},
			],
		},
	],
};
