import type { ResourceDefinition } from '../shared';
import { userIdParam } from '../shared';

export const alertsResource: ResourceDefinition = {
	name: 'Alerts',
	value: 'alerts',
	operations: [
		{
			name: 'Get Active',
			value: 'getActive',
			method: 'GET',
			path: '/APP/Alerts/getActive',
			description: 'Get active alerts',
			action: 'Get active alerts',
		},
		{
			name: 'Get Unread Counts',
			value: 'getUnreadCounts',
			method: 'GET',
			path: '/APP/Alerts/getUnreadCounts',
			description: 'Get unread alert counts',
			action: 'Get unread alert counts',
		},
		{
			name: 'Get History',
			value: 'getHistory',
			method: 'GET',
			path: '/APP/Alerts/getHistory',
			description: 'Get alert history',
			action: 'Get alert history',
		},
		{
			name: 'Add As Fan',
			value: 'addAsFan',
			method: 'POST',
			path: '/APP/Alerts/addAsFan',
			description: 'Accept user as fan',
			action: 'Accept user as fan',
			params: [userIdParam],
		},
		{
			name: 'Add All As Fan',
			value: 'addAllAsFan',
			method: 'POST',
			path: '/APP/Alerts/addAllAsFan',
			description: 'Accept all requests as fans',
			action: 'Accept all requests as fans',
		},
		{
			name: 'Add All As Friends',
			value: 'addAllAsFriends',
			method: 'POST',
			path: '/APP/Alerts/addAllAsFriends',
			description: 'Accept all requests as friends',
			action: 'Accept all requests as friends',
		},
		{
			name: 'Deny All',
			value: 'denyAll',
			method: 'POST',
			path: '/APP/Alerts/denyAll',
			description: 'Deny all pending alerts',
			action: 'Deny all pending alerts',
		},
		{
			name: 'Add As Friend',
			value: 'addAsFriend',
			method: 'POST',
			path: '/APP/Alerts/addAsFriend',
			description: 'Accept user as friend',
			action: 'Accept user as friend',
			params: [userIdParam],
		},
		{
			name: 'Deny Friendship',
			value: 'denyFriendship',
			method: 'POST',
			path: '/APP/Alerts/denyFriendship',
			description: 'Deny a friend request',
			action: 'Deny a friend request',
			params: [userIdParam],
		},
		{
			name: 'Remove Notification',
			value: 'removeNotification',
			method: 'POST',
			path: '/APP/Alerts/removeNotification',
			description: 'Remove a user notification',
			action: 'Remove a user notification',
			params: [userIdParam],
		},
	],
};
