import type { ResourceDefinition } from '../shared';
import { limitParam, offsetParam, userIdParam } from '../shared';

export const friendsFansResource: ResourceDefinition = {
	name: 'Friends And Fans',
	value: 'friendsFans',
	operations: [
		{
			name: 'Get Friends By Offset',
			value: 'getFriendsByOffset',
			method: 'GET',
			path: '/APP/FriendsFans/getFriendsByOffset',
			description: 'Get user friends',
			action: 'Get user friends',
			twoLegged: true,
			params: [
				userIdParam,
				{ ...offsetParam, default: 0, type: 'number' },
				{ ...limitParam, default: 10 },
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get Fans By Offset',
			value: 'getFansByOffset',
			method: 'GET',
			path: '/APP/FriendsFans/getFansByOffset',
			description: 'Get user fans',
			action: 'Get user fans',
			twoLegged: true,
			params: [
				userIdParam,
				{ ...offsetParam, default: 0, type: 'number' },
				{ ...limitParam, default: 10 },
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get Following By Offset',
			value: 'getFollowingByOffset',
			method: 'GET',
			path: '/APP/FriendsFans/getFollowingByOffset',
			description: 'Get followed users',
			action: 'Get followed users',
			params: [
				{ ...offsetParam, default: 0, type: 'number' },
				{ ...limitParam, default: 10 },
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
			],
		},
		{
			name: 'Become Friend',
			value: 'becomeFriend',
			method: 'POST',
			path: '/APP/FriendsFans/becomeFriend',
			description: 'Send a friend request',
			action: 'Send a friend request',
			params: [{ displayName: 'Friend ID', name: 'friend_id', type: 'string', default: '' }],
		},
		{
			name: 'Remove As Friend',
			value: 'removeAsFriend',
			method: 'POST',
			path: '/APP/FriendsFans/removeAsFriend',
			description: 'Remove a friend',
			action: 'Remove a friend',
			params: [{ displayName: 'Friend ID', name: 'friend_id', type: 'string', default: '' }],
		},
		{
			name: 'Become Fan',
			value: 'becomeFan',
			method: 'POST',
			path: '/APP/FriendsFans/becomeFan',
			description: 'Become a fan of a user',
			action: 'Become a fan of a user',
			params: [
				{ displayName: 'Fan ID', name: 'fan_id', type: 'string', default: '' },
				{ displayName: 'Follow', name: 'follow', type: 'boolean', default: false },
			],
		},
		{
			name: 'Set Following',
			value: 'setFollowing',
			method: 'POST',
			path: '/APP/FriendsFans/setFollowing',
			description: 'Set follow state for a user',
			action: 'Set follow state for a user',
			params: [
				userIdParam,
				{ displayName: 'Follow', name: 'follow', type: 'boolean', default: true },
			],
		},
		{
			name: 'Get Completion',
			value: 'getCompletion',
			method: 'GET',
			path: '/APP/FriendsFans/getCompletion',
			description: 'Get friend nickname completion data',
			action: 'Get friend nickname completion data',
		},
		{
			name: 'Get Friendship Requests',
			value: 'getFriendshipRequests',
			method: 'GET',
			path: '/APP/FriendsFans/getFriendshipRequests',
			description: 'Retrieve pending friendship requests',
			action: 'Get friendship requests',
		},
		{
			name: 'Set Following Replurk',
			value: 'setFollowingReplurk',
			method: 'POST',
			path: '/APP/FriendsFans/setFollowingReplurk',
			description: 'Set whether to follow a user’s replurks',
			action: 'Set following replurk state',
			params: [
				userIdParam,
				{ displayName: 'Follow', name: 'follow', type: 'boolean', default: true },
			],
		},
	],
};
