/* eslint-disable n8n-nodes-base/node-param-default-wrong-for-limit */
/* eslint-disable n8n-nodes-base/node-param-description-missing-from-limit */
/* eslint-disable n8n-nodes-base/node-param-min-value-wrong-for-limit */
import type { ResourceDefinition } from '../shared';
import {
	detailParams,
	idsParam,
	languageOptions,
	limitParam,
	offsetParam,
	plurkIdParam,
	qualifierOptions,
	timelineFilterParam,
	userIdParam,
} from '../shared';

export const timelineResource: ResourceDefinition = {
	name: 'Timeline',
	value: 'timeline',
	operations: [
		{
			name: 'Get Plurk',
			value: 'getPlurk',
			method: 'GET',
			path: '/APP/Timeline/getPlurk',
			description: 'Get a single Plurk',
			action: 'Get a single Plurk',
			params: [
				plurkIdParam,
				...detailParams,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get Plurk Counts Info',
			value: 'getPlurkCountsInfo',
			method: 'GET',
			path: '/APP/Timeline/getPlurkCountsInfo',
			description: 'Get counts for a Plurk',
			action: 'Get Plurk counts info',
			params: [plurkIdParam],
		},
		{
			name: 'Get Plurks',
			value: 'getPlurks',
			method: 'GET',
			path: '/APP/Timeline/getPlurks',
			description: 'Get timeline Plurks',
			action: 'Get timeline Plurks',
			params: [
				offsetParam,
				{ ...limitParam, default: 20 },
				timelineFilterParam,
				...detailParams,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get Unread Plurks',
			value: 'getUnreadPlurks',
			method: 'GET',
			path: '/APP/Timeline/getUnreadPlurks',
			description: 'Get unread Plurks from the timeline',
			action: 'Get unread Plurks',
			params: [
				offsetParam,
				limitParam,
				{ ...timelineFilterParam, default: 'all' },
				...detailParams,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get Public Plurks',
			value: 'getPublicPlurks',
			method: 'GET',
			path: '/APP/Timeline/getPublicPlurks',
			description: 'Get public Plurks for a user',
			action: 'Get public Plurks for a user',
			params: [
				userIdParam,
				{ displayName: 'Nick Name', name: 'nick_name', type: 'string', default: '' },
				offsetParam,
				{ ...limitParam, default: 30 },
				...detailParams,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
				{ displayName: 'Only User', name: 'only_user', type: 'boolean', default: false },
			],
		},
		{
			name: 'Add Plurk',
			value: 'plurkAdd',
			method: 'POST',
			path: '/APP/Timeline/plurkAdd',
			description: 'Post a new Plurk',
			action: 'Post a new Plurk',
			params: [
				{ displayName: 'Content', name: 'content', type: 'string', default: '', rows: 4 },
				{
					displayName: 'Qualifier',
					name: 'qualifier',
					type: 'options',
					default: 'says',
					options: qualifierOptions,
				},
				{
					displayName: 'Limited To',
					name: 'limited_to',
					type: 'json',
					default: '[]',
					description: 'JSON array of user IDs; [0] means friends only',
				},
				{ displayName: 'Excluded', name: 'excluded', type: 'json', default: '[]' },
				{
					displayName: 'No Comments',
					name: 'no_comments',
					type: 'number',
					default: 0,
					description: '0 allows comments, 1 disables comments, 2 allows friends only',
				},
				{
					displayName: 'Language',
					name: 'lang',
					type: 'options',
					default: 'en',
					options: languageOptions,
				},
				{ displayName: 'Replurkable', name: 'replurkable', type: 'number', default: 1 },
				{ displayName: 'Porn', name: 'porn', type: 'number', default: 0 },
				{
					displayName: 'Publish To Followers',
					name: 'publish_to_followers',
					type: 'number',
					default: 1,
				},
				{
					displayName: 'Publish To Anonymous',
					name: 'publish_to_anonymous',
					type: 'number',
					default: 1,
				},
				{
					displayName: 'Reaction Permission',
					name: 'reaction_permission',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Everyone', value: 'everyone' },
						{ name: 'Owner', value: 'owner' },
					],
				},
			],
		},
		{
			name: 'Delete Plurk',
			value: 'plurkDelete',
			method: 'POST',
			path: '/APP/Timeline/plurkDelete',
			description: 'Delete a Plurk',
			action: 'Delete a Plurk',
			params: [plurkIdParam],
		},
		{
			name: 'Edit Plurk',
			value: 'plurkEdit',
			method: 'POST',
			path: '/APP/Timeline/plurkEdit',
			description: 'Edit Plurk content',
			action: 'Edit Plurk content',
			params: [
				plurkIdParam,
				{ displayName: 'Content', name: 'content', type: 'string', default: '', rows: 4 },
				{
					displayName: 'No Comments',
					name: 'no_comments',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Allow Comments', value: '0' },
						{ name: 'Disable Comments', value: '1' },
						{ name: 'Friends Only', value: '2' },
					],
				},
				{ displayName: 'Limited To', name: 'limited_to', type: 'json', default: '[]' },
				{ displayName: 'Excluded', name: 'excluded', type: 'json', default: '[]' },
				{
					displayName: 'Replurkable',
					name: 'replurkable',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'False', value: 'false' },
						{ name: 'True', value: 'true' },
					],
				},
				{ displayName: 'Porn', name: 'porn', type: 'string', default: '' },
				{
					displayName: 'Reaction Permission',
					name: 'reaction_permission',
					type: 'options',
					default: '',
					options: [
						{ name: 'Unset', value: '' },
						{ name: 'Everyone', value: 'everyone' },
						{ name: 'Owner', value: 'owner' },
					],
				},
			],
		},
		{
			name: 'Toggle Comments',
			value: 'toggleComments',
			method: 'POST',
			path: '/APP/Timeline/toggleComments',
			description: 'Change comment setting on a Plurk',
			action: 'Change comment setting on a Plurk',
			params: [
				plurkIdParam,
				{
					displayName: 'No Comments',
					name: 'no_comments',
					type: 'number',
					default: 0,
					description: '0 allows comments, 1 disables comments, 2 allows friends only',
				},
			],
		},
		{
			name: 'Mute Plurks',
			value: 'mutePlurks',
			method: 'POST',
			path: '/APP/Timeline/mutePlurks',
			description: 'Mute one or more Plurks',
			action: 'Mute Plurks',
			params: [idsParam],
		},
		{
			name: 'Unmute Plurks',
			value: 'unmutePlurks',
			method: 'POST',
			path: '/APP/Timeline/unmutePlurks',
			description: 'Unmute one or more Plurks',
			action: 'Unmute Plurks',
			params: [idsParam],
		},
		{
			name: 'Favorite Plurks',
			value: 'favoritePlurks',
			method: 'POST',
			path: '/APP/Timeline/favoritePlurks',
			description: 'Favorite one or more Plurks',
			action: 'Favorite Plurks',
			params: [idsParam],
		},
		{
			name: 'Unfavorite Plurks',
			value: 'unfavoritePlurks',
			method: 'POST',
			path: '/APP/Timeline/unfavoritePlurks',
			description: 'Unfavorite one or more Plurks',
			action: 'Unfavorite Plurks',
			params: [idsParam],
		},
		{
			name: 'Replurk',
			value: 'replurk',
			method: 'POST',
			path: '/APP/Timeline/replurk',
			description: 'Replurk one or more Plurks',
			action: 'Replurk one or more Plurks',
			params: [idsParam],
		},
		{
			name: 'Unreplurk',
			value: 'unreplurk',
			method: 'POST',
			path: '/APP/Timeline/unreplurk',
			description: 'Undo replurk on one or more Plurks',
			action: 'Undo replurk on one or more Plurks',
			params: [idsParam],
		},
		{
			name: 'Mark As Read',
			value: 'markAsRead',
			method: 'POST',
			path: '/APP/Timeline/markAsRead',
			description: 'Mark Plurks as read',
			action: 'Mark Plurks as read',
			params: [
				idsParam,
				{
					displayName: 'Note Position',
					name: 'note_position',
					type: 'boolean',
					default: false,
					description: 'Whether to also update responses_seen',
				},
			],
		},
		{
			name: 'Upload Picture',
			value: 'uploadPicture',
			method: 'POST',
			path: '/APP/Timeline/uploadPicture',
			description: 'Upload an image to Plurk CDN',
			action: 'Upload an image to Plurk CDN',
			fileParam: {
				apiName: 'image',
				defaultBinaryProperty: 'data',
				description: 'Binary property that contains the image to upload',
			},
		},
		{
			name: 'Report Abuse',
			value: 'reportAbuse',
			method: 'POST',
			path: '/APP/Timeline/reportAbuse',
			description: 'Report Plurk abuse',
			action: 'Report Plurk abuse',
			params: [
				plurkIdParam,
				{
					displayName: 'Category',
					name: 'category',
					type: 'options',
					default: 'spam',
					options: [
						{ name: 'Others', value: 'others' },
						{ name: 'Porn', value: 'porn' },
						{ name: 'Privacy', value: 'privacy' },
						{ name: 'Spam', value: 'spam' },
						{ name: 'Violence', value: 'violence' },
					],
				},
				{ displayName: 'Reason', name: 'reason', type: 'string', default: '', rows: 3 },
			],
		},
		{
			name: 'Set Porn',
			value: 'setPorn',
			method: 'POST',
			path: '/APP/Timeline/setPorn',
			description: 'Update the Plurk porn flag',
			action: 'Set Plurk porn flag',
			params: [plurkIdParam, { displayName: 'Porn', name: 'porn', type: 'number', default: 0 }],
		},
		{
			name: 'Set Unread Snapshot',
			value: 'setUnreadSnapshot',
			method: 'POST',
			path: '/APP/Timeline/setUnreadSnapshot',
			description: 'Create an unread snapshot marker',
			action: 'Set unread snapshot',
			params: [{ ...timelineFilterParam, default: 'all' }],
		},
		{
			name: 'Get Snapshot Unread Plurks',
			value: 'getSnapshotUnreadPlurks',
			method: 'GET',
			path: '/APP/Timeline/getSnapshotUnreadPlurks',
			description: 'Retrieve unread Plurks from a snapshot',
			action: 'Get snapshot unread Plurks',
			params: [
				{ ...timelineFilterParam, default: 'all' },
				{ displayName: 'Index', name: 'index', type: 'number', default: 0 },
				{
					displayName: 'Limit',
					name: 'limit',
					type: 'number',
					default: 0,
					typeOptions: { minValue: 0 },
				},
				...detailParams,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
				{ displayName: 'Snapshot', name: 'snapshot', type: 'boolean', default: false },
			],
		},
		{
			name: 'Mark All As Read',
			value: 'markAllAsRead',
			method: 'POST',
			path: '/APP/Timeline/markAllAsRead',
			description: 'Mark all Plurks as read',
			action: 'Mark all Plurks as read',
			params: [
				{ ...timelineFilterParam, default: 'all' },
				{ displayName: 'Exclude IDs', name: 'exclude_ids', type: 'json', default: '[]' },
			],
		},
	],
};
