import type { ResourceDefinition } from '../shared';
import { plurkIdParam, qualifierOptions } from '../shared';

export const responsesResource: ResourceDefinition = {
	name: 'Responses',
	value: 'responses',
	operations: [
		{
			name: 'Get',
			value: 'get',
			method: 'GET',
			path: '/APP/Responses/get',
			description: 'Get responses for a Plurk',
			action: 'Get responses for a Plurk',
			twoLegged: true,
			params: [
				plurkIdParam,
				{ displayName: 'From Response', name: 'from_response', type: 'number', default: 0 },
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
				{ displayName: 'Count', name: 'count', type: 'number', default: 0 },
				{ displayName: 'Only Owner', name: 'only_owner', type: 'boolean', default: false },
			],
		},
		{
			name: 'Get By ID',
			value: 'getById',
			method: 'GET',
			path: '/APP/Responses/getById',
			description: 'Get responses from a response ID',
			action: 'Get responses by ID',
			twoLegged: true,
			params: [
				plurkIdParam,
				{ displayName: 'From Response ID', name: 'from_response_id', type: 'number', default: 0 },
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
				{ displayName: 'Count', name: 'count', type: 'number', default: 0 },
			],
		},
		{
			name: 'Get Around Seen',
			value: 'getAroundSeen',
			method: 'GET',
			path: '/APP/Responses/getAroundSeen',
			description: 'Get responses around the seen position',
			action: 'Get responses around seen',
			twoLegged: true,
			params: [
				plurkIdParam,
				{ displayName: 'Minimal Data', name: 'minimal_data', type: 'boolean', default: false },
				{ displayName: 'Minimal User', name: 'minimal_user', type: 'boolean', default: false },
				{ displayName: 'Count', name: 'count', type: 'number', default: 0 },
			],
		},
		{
			name: 'Add Response',
			value: 'responseAdd',
			method: 'POST',
			path: '/APP/Responses/responseAdd',
			description: 'Add a response to a Plurk',
			action: 'Add a response to a Plurk',
			params: [
				plurkIdParam,
				{ displayName: 'Content', name: 'content', type: 'string', default: '', rows: 4 },
				{
					displayName: 'Qualifier',
					name: 'qualifier',
					type: 'options',
					default: 'says',
					options: qualifierOptions,
				},
			],
		},
		{
			name: 'Delete Response',
			value: 'responseDelete',
			method: 'POST',
			path: '/APP/Responses/responseDelete',
			description: 'Delete a response',
			action: 'Delete a response',
			params: [
				{ displayName: 'Response ID', name: 'response_id', type: 'number', default: 0 },
				plurkIdParam,
			],
		},
		{
			name: 'Edit',
			value: 'edit',
			method: 'POST',
			path: '/APP/Responses/edit',
			description: 'Edit a response',
			action: 'Edit a response',
			params: [
				plurkIdParam,
				{ displayName: 'Response ID', name: 'response_id', type: 'number', default: 0 },
				{ displayName: 'Content', name: 'content', type: 'string', default: '', rows: 4 },
			],
		},
		{
			name: 'Report Abuse',
			value: 'reportAbuse',
			method: 'POST',
			path: '/APP/Responses/reportAbuse',
			description: 'Report response abuse',
			action: 'Report response abuse',
			params: [
				plurkIdParam,
				{ displayName: 'Response ID', name: 'response_id', type: 'number', default: 0 },
				{ displayName: 'Category', name: 'category', type: 'string', default: '' },
				{ displayName: 'Reason', name: 'reason', type: 'string', default: '', rows: 3 },
			],
		},
	],
};
